<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>

    <AssemblyName>AUCaptainRoleMod</AssemblyName>
    <RootNamespace>AUCaptainRoleMod</RootNamespace>

    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>

    <Reference Include="Assembly-CSharp">
      <HintPath>libs\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="BepInEx.Core">
      <HintPath>libs\BepInEx.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>libs\BepInEx.Unity.IL2CPP.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="0Harmony">
      <HintPath>libs\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.CoreModule">
      <HintPath>libs\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>libs\Il2CppInterop.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2CppSystem">
      <HintPath>libs\Il2CppSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2CppMscorlib">
      <HintPath>Il2CppInterop\net472\Il2CppMscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>

  </ItemGroup>

</Project>
