<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsing>enable</ImplicitUsing>
    <Nullable>enable</Nullable>
    <AssemblyName>AUCaptainRoleMod</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <!-- Forces the compiler to link the internal Il2Cpp metadata structures directly by name -->
    <Reference Include="Assembly-CSharp">
      <HintPath>libs\Assembly-CSharp.dll</HintPath>
      <Aliases>global,Il2Cpp</Aliases>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>libs\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Core">
      <HintPath>libs\BepInEx.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>libs\BepInEx.Unity.IL2CPP.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>libs\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>libs\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>libs\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSystem">
      <HintPath>libs\Il2CppSystem.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppMscorlib">
      <HintPath>Il2CppInterop\net472\Il2CppMscorlib.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
